TandoorRecipes/recipes

cookbook/templates/meal_plan.html, cookbook/views/new.py
Hey, hope you don't mind me barging in :) I've been meaning to replace my own homegrown unfinished recipe manager and stumbled upon yours. I might run this for myself with some modifications and figured you might like some of them. 
This adds some buttons to the meal planner that open the new-meal-plan form with the `date` and `meal` fields prefilled.
=> Add buttons to add a meal plan to a specific point in time

cookbook/templates/recipe_view.html
This makes any links that you put into your recipe clickable. I use this when i'm too lazy to fill in the recipe right away and just paste the link as a placeholder.
=> Make links in recipe clickable

cookbook/tables.py, cookbook/templates/recipes_table.html
Attached is a suggested change to make it so you can click on the picture of the recipe (or the blank image supplied) to proceed to the instructions. As of right now, you have to click on the name of the recipe, and the image has no hyperlink. (Note, this only works at all if using the "Search Style: Large" setting.)
I'm honestly not super well-versed on Django so it was a bit of a stumble through. I also broke out the added elements with variables since much of the tags are reused. Obviously those could be simplified into one line (in [cookbook/tables.py](https://github.com/vabene1111/recipes/blob/445c01bddc6bbf3f195d6cec67dcd18e656629ed/cookbook/tables.py#L11)) as so:
```
def render(self, value):
if value.url:
return mark_safe(f'<img src="{value.url}" alt="{_("Recipe Image")}" …
```
=> Made recipe images hyperlinked

docs/docker/nginx-proxy with proxy authentication/README.md, docs/docker/nginx-proxy with proxy authentication/docker-compose.yml, docs/docker/nginx-proxy with proxy authentication/nginx/conf.d/Recipes.conf, recipes/middleware.py, recipes/settings.py
See #81.
This Pull Request will allow you to log in to recipes by looking for a matching request header. If there is no matching header, Django automatically falls back to using the built-in/standard User/Password login functionality of `django.contrib.auth.backends.ModelBackend` (i.e., what is currently used.)
If the user _does not exist in recipes_, but does have access granted via the authentication server, Django silently lets the user access the site, but will not _create_ that user in the database:
I tried to add some documentation/deployment details as well, but, given this also requires a functioning authentication server, which could have lots of different implementations, it's rather sparse. I'm happy to expand upon that, though, if needed.
Let me know if there any issues!
=> Adding Reverse Proxy Authentication

cookbook/templates/index.html, cookbook/templates/recipe_view.html, cookbook/templates/url_import.html
- Add min (`1`) and max (`999`) to the servings spinner on the recipe view
- Made the text next to the checkbox the label instead of the title for the `All Keywords` check on website import (fixes #278)
- Add the `show` class to the advanced search element if you searched with the advanced search
=> Minor improvements

cookbook/helper/ingredient_parser.py, cookbook/helper/recipe_url_import.py
The previous implementation of parsing ingredients was very simple. I now wrote a parser
that I would consider good. It takes care of several edge cases and notations.
- Supports fraction unicode (½, ¼, ⅜, ...)
- Supports notations like `1½` and `1 1/2`
- Supports unit directly after the amount without space inbetween (`2g`, `2½g`)
- Supports notes (`5g onion (cubed)` -> amount: 5, unit: g, ingredient: onion, note: cubed)
- Supports notes (`5g onion, cubed` -> amount: 5, unit: g, ingredient: onion, note: cubed)
- Does not break when both commas and brackets exist
=> Improve text to ingredient parsing

cookbook/helper/ingredient_parser.py, cookbook/tests/other/test_edits_recipe.py
The new Ingredient Parser failed to parse ingredients like "400 g Karotte(n)", as it will try to match closing brackets with opening brackets only at the start of tokens.
This PR tries to fix that.
Also, the testcases always succeeded, as the wrong function was called and the result was checked for inequality instead of equality.
=> Fix ingredient parser to allow Plural-suffixes

cookbook/helper/ingredient_parser.py, cookbook/tests/other/test_edits_recipe.py
Even though ingredients like '1 1/2 something' already worked fine and got converted to 1.5 something
I just came across a recipe using '1/2' as the whole amount without any whole number before that.
Apparently I overlooked that case before so I now also fixed that.
=> Fix ingredient parsing for fractions using '/'

.env.template, recipes/settings.py
Thanks for your work!
When trying to connect to connect to a postgres secured with TLS it failed to connect. With this PR it works:
```
docker run --rm -ti --name recipes -e DB_ENGINE=django.db.backends.postgresql_psycopg2 -e POSTGRES_HOST=recipes-db-postgres-cluster-postgres -e DB_OPTIONS='{"sslmode":"require"}' angelnu/recipes
```
=> Add DB_OPTIONS to enable DBs with SSL

cookbook/helper/recipe_url_import.py, cookbook/tests/api/test_api_keyword.py, cookbook/views/data.py
when importing a recipe that includes keywords already in use it attempts to create a duplicate name, causing an integrity error.
Also fixed URL import when servings are stored as a list.
I also added a couple of tests on keywords.
=> Import recipe duplicate keyword fix

cookbook/integration/cheftap.py, docs/features/import_export.md
When I submitted my testing .zip, I didn't submit my normal export, because that has some personal data in the recipes. Instead, I made one by had, which was a mistake. The folder contained inside is also called cheftap_export. This fixes the code and the docs for ChefTap imports.
=> Cheftap import tweak

cookbook/integration/paprika.py
* Fixes a crash on KeyError if `photo_data` does not exist in `recipe_json`.
* Also fixes a crash if `photo_data` is an empty string.
=> Fix crash on missing photos in paprika

cookbook/helper/scrapers/scrapers.py
had to catch an additional exception to TextScraper that occurs on bookmarklet that doesn't happen during live scrape
=> minor bug fix in bookmarklet

vue/src/apps/RecipeView/RecipeView.vue
This fixes #526 and #325
I guess there is no reason to set the text direction to rtl.
To keep the styling I added the text-align: right.
The search didn't show any css that depends on the rtl attribute on purpose, so I guess this should not have styling side affects.
=> Fix servings input field text direction

cookbook/forms.py, cookbook/integration/integration.py, cookbook/integration/recettetek.py, cookbook/views/import_export.py
This PR adds an importer for RecetteTek - [https://www.recettetek.com/en/](https://www.recettetek.com/en/)
It is currently possible to import either a single recipe or import all exported recipes at once.
RecetteTek allows a user to export their recipes as either an '.RTK' file or an '.HTML' file, this importer supports only the RTK format.
It will also attempt to download the original image that RecetteTek initially imported, but if that fails it will not import any image. The recipe export from RecetteTek does include the original images locally, but I have yet to look at the best way to import those.
A lot of the fields that RecetteTek have are free-form, so things like serving size, prep time, cooking time etc will fail to import if there is anything other than an integer in the …
=> New Importer - RecetteTek

cookbook/helper/recipe_url_import.py, cookbook/tests/other/_recipes.py
one of the tests - thespruceeats.com - is still broken due to upstream bug, which has been reported.
=> updated url import and test due to updated recipe_scraper

docs/install/manual.md
I just went through a manual install on DietPi / Debian Unstable, and found that the manual needed some improving, this method works, whereas following the original manual was not a success for me.
The only line I would say I am unsure about is this one:
"Give the user permissions: `chown -R recipes:www-data /var/www/recipes`"
As I am not sure whether these permissions are necessary for this to work.
Hope this is useful, let me know if I can make further improvements.
=> Update manual setup

docs/install/manual.md
In order to run over HTTPS* django requires the X-Forwarded-Proto header sent from the nginx proxy. I didn't add everything needed for TLS, but this header works with HTTP and HTTPS so I figure it might save a few people some time if they ever decide to secure their installation.
\* specifically, I noticed that image URLs are requested over HTTP instead of HTTPS even when the main page is HTTPS until this header is sent
=> Send proper protocol to Django from Nginx

README.md
The Docker installation URL in README seems outdated, so I replaced it with the working one.
=> README: Fix Docker installation URL

.env.template, cookbook/admin.py, cookbook/models.py, cookbook/tests/api/test_api_food.py, cookbook/tests/api/test_api_keyword.py, cookbook/views/api.py, recipes/settings.py, recipes/wsgi.py
Allows disabling sort_tree in ENV variable (enabled by default)
Admin function to manually sort tree
Admin function to Enable/Disable tree sorting (will revert to ENV value on app restart)
At app startup run fix_tree - will resolve any problems found (includes sorting nodes if switching between sorted/unsorted)
> nodes with characters not found in the alphabet
> nodes when a wrong path length according to steplen
> orphaned nodes
> nodes with the wrong depth value for their path
> wrong number of children
=> Sort tree enhancements

vue/src/components/RecipeCard.vue
Currently, the working/waiting time is only shown on cards if there is a waiting time. This pull request shows the working time, even if no waiting time is set.
=> Also show working/waiting time if only one of both is set

vue/src/apps/RecipeEditView/RecipeEditView.vue
When editing the recipe for the first time, I was unsure of the time unit to use. Minutes makes the most sense, but I figure adding it in the label will help others in the future.
=> Add time unit hint to recipe edit view

.github/workflows/docs.yml, docs/contribute.md, docs/install/docker.md, mkdocs.yml
This PR revises previous defunc #1058.
The inproper PR occured because testing was locally done with `mkdocs serve`. At this point I did not realize that `docs/index.md` contained absolute URLs to the install section of the documentation, hence linking to `https://docs.tandoor.dev/install/docker/` - and not the locally built section of the documentation.
As a result the respective documentation looked correct - when it actually was not!
Using encapsulation of included file contents via
```
~~~yaml
{% include "./relative/docker-compose.yml" %}
~~~
```
This PR is now tested in a live environment: [Check it here](https://tuxuser.github.io/recipes/install/docker/)
=> Docs: Inline docker yaml files (revises #1058)

cookbook/serializer.py, vue/package.json
eslint and vue-simple-calendar both have breaking changes and shouldn't be upgraded until they are resolved.
```
"eslint": "^7.28.0",
"vue-simple-calendar": "^5.0.1",
```
=> fix package.json

cookbook/helper/HelperFunctions.py, cookbook/helper/recipe_search.py, cookbook/serializer.py, cookbook/views/api.py, recipes/middleware.py, recipes/settings.py, vue/src/apps/RecipeSearchView/RecipeSearchView.vue, vue/src/locales/en.json
create RecipeFacet class
build tree facets through queryset instead of iteration
async load children of tree facets
move images, recipe count to queryset instead of SerializerMethodField
fixes #1232 
changes behavior of 'OR' search #1022
=> Performance refactor

.github/ISSUE_TEMPLATE/bug_report.md
To get more information about bugs and prohibit having to ask one by one for specific information, I extended and redesigned the bug template.
Fell free to change parts or suggest changes.
Please note, that all explanatory parts are hidden as comments in the markdown (which the user will see when creating a bug ticket) so they don't unnecessarily clutter the finished bug report.
=> Extension and hopefully simplification of bug reporting process

recipes/settings.py
Currently there is no possibility to move the location of `db.sqlite3` out of `/opt/recipes`. This pull request allows to specify full paths via `DATABASE_URL`, e.g.:
```
sqlite://nobody@nowhere/db/db.sqlite3
```
This will not access `/opt/recipes/db.sqlite` but `/opt/recipes/db/db.sqlite`.
=> Allow to specify an actual path using DATABASE_URL

docs/features/authentication.md
Providing an example to integrate Keycloak as IAM for Tandoor. Hinting that both SOCIAL* variables are required.
=> Example for third-party authentication

vue/src/apps/MealPlanView/MealPlanView.vue
#1093 add a recipe link into meal plan
I'm not experiences with Vue or Javascript development in general.
So please feel free to do any cleanup you see fit.
I coult not find a way to hide the context menu item if no receipt was linked to the meal plan entry.
=> #1093 Recipe link in plan

.env.template
Add hint about trailing slashes for subpath setups due to recent issue on Discord.
=> Add hint about trailing slashes for subpath setups

docs/install/kubernetes.md
The docs mention an incorrect path to the kubernetes yaml files. This PR aims to correct that.
=> Correct path to kubernetes files

vue/src/components/MealPlanCalenderHeader.vue
Made a small change to the font size so longer months won't affect arrow buttons. I think this helps the meal plan calendar look more aesthetic.
Here's an example: 
(before)
(after)
=> Simple font size change

.env.template, docs/features/authentication.md, recipes/settings.py
My ldap server uses TLS encryption with self signed certificates. With this PR it's possible to set the ca cert file used in ldap authentication to check the ldap server certificate via an optional environment variable. Details can be found [here](https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html#ldap.OPT_X_TLS_CACERTFILE).
=> Add new env parameter to set ldap ca cert file

docs/faq.md, docs/install/docker.md
Added example configs for plain local nginx and Apache2.
Also added FAQ section for all generic issues when not setting all required headers correctly.
Added section for required headers in the Docker installation docs.
I hope this reduces the amount of "header-issues" which seem to be a constant issue-source.
As always, feel free to adjust.
=> [Docs] Added example configs and header information

docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/plain/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml
Fixes the setup issue almost all Raspberry Pi users have and probably some others with slow or low spec systems.
The web_recipes container waits for db_recipes to be healthy.
db_recipes is healthy, as soon as postgres is completely ready.
Note: ps_isready doesn't work here for some reason.
Tested multiple times with a Raspberry Pi 4.
=> [Docker] Web_recipes waits for db_recipes to be ready

.dockerignore
ignore node_modules at every directory depth
ignore .vue and .ts files
ignore mediafiles/staticfiles/sqlitedb
ignore pytest configs/folders
ignore openapi generator
=> updated .dockerignore

cookbook/templates/settings.html
The final `}` in this piece of code should've been included in the comment. 
This PR fixes it.
This fixes a spurious `}` preventing the whole code block from being loaded. `applyPresets` was broken because of this. 
Also formatted the JS to look alike.
=> Fixed JS parsing error on settings page

docs/install/docker/ipv6_plain/docker-compose.yml
This version makes use of a separate user defined network and allows to run tandoor in IPv6 native (if configured correctly, you will not need a reverse proxy like traefik/nginx etc.) Keep in mind to adjust the firewall rules accordingly to not expose services you do not want to be exposes (eg. django-server-container of tandoor).
=> Added docker compose file for IPv6 native

vue/src/apps/RecipeView/RecipeView.vue
To resolve #1434
This is rather basic, at some point you could add a switch to toggle this functionality on & off.
=> Keep screen awake when viewing recipe

boot.sh, docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/plain/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml
Undid the depends_on change in the docker-compose file, since it requires a fairly recent docker-compose version (>= 1.27.0) and can therefore cause issues in some cases.
In general, this should be handled by the requester - so the web-container - anyway.
`boot.sh` now retries every 5 seconds when the `python manage.py migrate` command exits with error code `1`.
This error code is thrown, when the DB (container) is not reachable yet (the exact error we're trying to tackle here). Also, when there is a misconfiguration like renamed db-container, where retries won't help but it doesn't hurt either - still worth it imo since it's an easy fix in the boot.sh like this.
Other errors I could provoke exited with error 130 so not all exit with a 1.
Success is obviously 0.
Tested with a Raspberry Pi …
=> Moved DB-waiting from docker-level to container-level

Dockerfile, boot.sh
In #1498 I added a retry functionality for the migration.
Since blindly retrying migrations can be dangerous since I'd see it as blindly messing with data, knowing something isn't right, I decided to look for a better solution (and also reduce log spam drastically).
With this, the PostgreSQL server in POSTGRES_HOST (e.g. db_recipes) will be pinged before migration.
The only downside to this is the necessity to add postgresql as additional dependency which increases image size slightly.
If someone knows another way to get access to the pg_isready command, please let me know.
=> Ping DB instead of trying migration

docs/install/k8s/40-sts-postgresql.yaml
@TomHutter tagging you here, because you did the main work on this docs. 
Found some dupplicate declarations in the `40-sts-postgresql.yaml`, which should be fixed with this commit.
=> K8s deployment: Small fix for dupplicate entries.

boot.sh
Checks on Web-Container startup, whether the Nginx configuration file (Recipes.conf) is present.
If it's not present - which would prohibit Nginx from working properly (see #1531) - a warning is shown.
If GUNICORN_MEDIA is not 0 (0 is default) and therefore Nginx is not used, no warning will be shown.
Path to config file is hardcoded, but there is no point in changing the mounting point in the docker-compose file anyway and the warning doesn't prohibit the startup - it's just to make issue analysis for the users and developers easier.
=> Added existence check for Nginx config file and mandatory parameters

vue/src/apps/RecipeSearchView/RecipeSearchView.vue
Small changes to render some search related controls better, especially in languages with longer words (German here) and correcting the vertical alignment between label and control in all languages.
=> Optimized advanced search settings UX

vue/src/apps/RecipeEditView/RecipeEditView.vue, vue/src/locales/de.json, vue/src/locales/en.json
Multiselect controls are now fully localized in RecipeEditView.
Added English and German version to json files already.
Localized strings:
- "List is empty"
- "Press enter to remove"
- "Selected"
- "Select"
- "Add [<element name>]"
I can apply this to other vue pages as well if you don't mind. If so, you can leave this PR open, so I can add commits for each page to it.
=> Multiselect controls are now fully localized in RecipeEditView

Dockerfile
Fixes #1619
Added ldap as runtime dependency to Dockerfile since the new Alpine image seems to have removed that.
Thanks for the hint: https://github.com/TandoorRecipes/recipes/issues/1619#issuecomment-1058325544
=> Added ldap as runtime dependency to Dockerfile

cookbook/helper/recipe_url_import.py
When testing the import with version 13.19.0 of recipe-scraper, I realized that we do not use all information the scraper object may provide.
Especially when a recipe was scraped that didn't support Schema.org, scrape_me provides fields only through the respective scraper methods and not through its `schema.data` attribute.
Added support for
* `scrape.description()`
* `scrape.prep_time()`
* `scrape.cook_time()`
* Keywords from `scrape.cuisine()` and `scrape.category()`
If these properties return an exception the fallback is to use the old behaviour and try to get the data from the schema object directly.
getting the URL from `scrape.canonical_url()` instead of from `scrape.url` also can't screw anything up since in the recipe_scraper library the default implementation of `canonical_url` …
=> Improve recipe import for non schema.org recipes

cookbook/locale/ca/LC_MESSAGES/django.po, cookbook/locale/de/LC_MESSAGES/django.po, cookbook/locale/en/LC_MESSAGES/django.po, cookbook/locale/es/LC_MESSAGES/django.po, cookbook/locale/fi/LC_MESSAGES/django.po, cookbook/locale/fr/LC_MESSAGES/django.po, cookbook/locale/hu_HU/LC_MESSAGES/django.po, cookbook/locale/it/LC_MESSAGES/django.po, cookbook/locale/lv/LC_MESSAGES/django.po, cookbook/locale/nl/LC_MESSAGES/django.po, cookbook/locale/pt/LC_MESSAGES/django.po, cookbook/locale/pt_BR/LC_MESSAGES/django.po, cookbook/locale/rn/LC_MESSAGES/django.po, cookbook/locale/ro/LC_MESSAGES/django.po, cookbook/locale/ru/LC_MESSAGES/django.po, cookbook/locale/sl/LC_MESSAGES/django.po, cookbook/locale/tr/LC_MESSAGES/django.po, cookbook/locale/zh_CN/LC_MESSAGES/django.po, cookbook/locale/zh_Hant/LC_MESSAGES/django.po, cookbook/templates/system.html, cookbook/views/new.py
Gunicoren should be Gunicorn
Send should be Sent. (Also reworded more clearly)
=> Fixed typos and grammatical issues.

docs/install/docker.md
Docker bind mounts have to use absolute paths (https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount).
The `docker run` command as it was in the docs fails when using the relative mounts `./staticfiles` and `./mediafiles.`
Relative path mounts may be supported in the future but not a lot of progress was made there recently (https://github.com/docker/cli/issues/1203)
=> Update bind mounts in docker run command to use absolute paths

docs/install/manual.md
- apt install of nodejs installs an unsupported (V10.X) version
- dependencies for python-ldap were missing
=> Updated dependencies of manual setup

boot.sh
Add POSTGRES_USER to psql health check during boot to support external psql instances better.
Fixes #1656
=> Add POSTGRES_USER to psql health check during boot

docs/install/k8s/10-configmap.yaml, docs/install/k8s/15-secrets.yaml, docs/install/k8s/20-service-account.yaml, docs/install/k8s/30-pvc.yaml, docs/install/k8s/40-sts-postgresql.yaml, docs/install/k8s/45-service-db.yaml, docs/install/k8s/50-deployment.yaml, docs/install/k8s/60-service.yaml, docs/install/k8s/70-ingress.yaml
The namespace prevents installing into a custom namespace. 
Also, "default" is the default namespace and does not need to be specified.
=> Remove namespace vom k8s templates

docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/plain/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml
Following a support request and discussion in discord this PR aims to reintroduce the `restart: always` policy for the tandoor web-service container in the standard docker-compose.yml.
It is unexpected for new admins or users unfamiliar with docker-compose that all containers except for tandoor-web restart after a reboot.
Restart loops were the reason why `restart: always` was removed in https://github.com/TandoorRecipes/recipes/pull/1498
I think it's acceptable behaviour that such restart loops happen when the configuration is faulty and thus the container crashes.
=> Docs: Reintroduce restart-always to web_recipes service

cookbook/static/css/app.min.css, cookbook/templates/base.html
The navbar logo had a height of `5vh` wich ich relative to the screen size and results in a very big logo on bigger screens like a 1440p screen (see first image). This PR does two things to make the logo look better on multiple screens.
- Use a fixed height, in this case `40px` for every screen size.
- Use the already existing `svg` image instead of the `png` wich can get blurry depending on the scaling.
Additionally I swapped the logo and menu button on mobile screens. Since there is no Navigation Drawer as known from Material design, there is no point in moving the Logo to the right on mobile. It looks more consistent if the logo stays at the same place for all screen sizes.
I'd like to hear what you think about these changes.
old:
new:
old:
new:
=> Navbar tweaks

cookbook/locale/de/LC_MESSAGES/django.po
This fixes a link in the German locale, similar to #1698. I guess the proper way would be to fix this in Weblate but I have no access there. So feel free to merge this PR or apply the changes in Weblate, whatever is easier for you.
=> Fix link in German locale

Dockerfile-raspi
This fixes the runtime errors of missing libs for the raspberry armv7 docker image.
I also excluded some unnecessary build dependencies.
I could only test it with qemu emulation and only with sqlite so maybe it should still be considered beta-ish. There could be some runtime problems because the piwheels wheels are built for raspbian and not for alpine.
=> Build pillow for armv7/ raspi

cookbook/helper/recipe_html_import.py, cookbook/helper/recipe_url_import.py, cookbook/helper/scrapers/scrapers.py
This PR fixes several import problems which stem from using some internal recipe-scrapers classes.
Overview over changes:
* If an url is provided, scrape_me is called in wild mode
* If a scraper for the url exists, this scraper is called by recipe-scrapers
* If no scraper exists wild_mode comes into effect and tries to search the page for schema.org fields.
* If this is unsuccesfull or no url was provided (which happens when data is entered in the source field) the old way of wrapping the input into `<script type='application/ld+json'> ... </script>` and then sending this into recipe-scrapers is used. (This is now the only way how `text_scraper` in `cookbook/helper/scrapers/scrapers.py` gets called)
* Additionally, we always try to get data from the property classes first. If that fails …
=> Fix import with recipe-scrapers

cookbook/static/themes/tandoor.min.css, vue/src/components/CustomInputSpinButton.vue, vue/src/components/IngredientComponent.vue, vue/src/components/IngredientsCard.vue
I fixed some issues with the print output that some elements were not hidden in print mode.
---
In addition to the issues, I fixed there is another issue, I could not fix. In print mode, the border around the portions selector should disappear. Currently, this is not possible, because in tandoor.min.css on line 10444 is this style, and the `!important` makes it impossible, to override this from inside a component (because the CSS selector is very strong):
```css
textarea, input:not([type="submit"]):not([class="multiselect__input"]):not([class="select2-search__field"]):not([class="vue-treeselect__input"]), select  {
background-color: white !important;
border-radius: .25rem !important;
border: 1px solid #ced4da !important;
}
```
Since I do not know what the overall effect of removing the …
=> Fix some issues to improve the print output

recipes/settings.py
Added in Django 4.0: CsrfViewMiddleware verifies the [Origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin), if provided by the browser, against the current host and the [CSRF_TRUSTED_ORIGINS](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS) setting. This provides protection against cross-subdomain attacks.
It broke this mechanism for installations behind proxy when origin is forwarded.
=> fixed csrf

.env.template, recipes/settings.py
Add a setting for https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#cloudfront `AWS_S3_CUSTOM_DOMAIN`. This instructs django to use a different domain than the S3 endpoint in image url's.
This fixes #1943 in the sense that setups with a private S3 can setup a public proxy (with limited access rights) to this proxy.
=> Add S3_CUSTOM_DOMAIN settings, closes #1943

cookbook/views/api.py
This solves two n+1 problems for the FoodViewSet
=> prefetch food relations #1965

vue/src/apps/RecipeView/RecipeView.vue, vue/src/components/RecipeCard.vue, vue/src/utils/utils.js
Adds an option to have time split into minutes and hours. It seems most languages understand "h", "min" notation, so I've stuck with that.
=> Solves #1830 (Split times over 60 min into hours and minutes)

cookbook/helper/ingredient_parser.py, cookbook/tests/other/test_ingredient_parser.py
Before this change the ingredient string for non-latin languages was not being parsed into the correct amount or units when the food is found at the start of the ingredient string.
This was because the regex being used was restricted to latin characters.
With this change the amount and units are correctly parsed from such a string.
Fixes https://github.com/TandoorRecipes/recipes/issues/1983
=> fix: ingredient parsing for non-latin languages

cookbook/helper/mdx_urlize.py
See [the release notes](https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md#previously-deprecated-objects-have-been-removed) about the removal of the deprecated argument.
=> Fix 'markdown' 3.4 version incompatibility 

cookbook/templates/account/login.html
Here is my suggestion for the Login page GUI: removing the yellow button unifies the UI in mobile/web view. I think that the user is more familiar with this UI since most of the reset password buttons are composed by some plain text and a `<a>` tag (not colored buttons).
_hacktoberfest 2022 entry_
=> Remove yellow button to unify GUI of reset password in mobile/web viewports #2102

cookbook/views/api.py
I got an error `"sharing_disabled"` when I tried to share a recipe (sharing was enabled and I'm a member of the user group). The reason seems to be that the permission check uses `has_group_permission` with `'user'` instead of `('user',)` (it was interpreted as a list of characters).
=> Fix share permission check

docs/install/manual.md
1) add the "Install project requirements" to the update commands list 
2) add infos from #1981 to doku  
I think it is helpful to mention briefly here that problems can occur. Even if it is not necessary for every update.
=> Update Doku for manual Installation 

mkdocs.yml
I think mkdocs-material's search function would be a great addition to make the documentation even more accessible. At least I was looking for some info just moments ago and would've liked a search bar.
From my own projects, I remembered that mkdocs-material does come with the search search plugin enabled by default. But it must be re-added to mkdocs.yml when other plugins are used. So I did. Hope this helps. :)
=> Enable search plugin for docs

docs/install/docker/plain/docker-compose.yml
the actual webserver is running on port 8080 and on the web_recipes service, as per all the documentation. 80 will not work, at least on the latest patch.
=> Fixed: ports are on the wrong service

docs/install/manual.md
[According to gixy](https://github.com/yandex/gixy/blob/master/docs/en/plugins/aliastraversal.md) the example nginx config for manual installation is vulnerable to a path traversal attack
=> Fix path traversal in manual installation steps

.github/workflows/build-docker.yml
This PR addresses an issue where CI has been failing for Dependabot PRs after #2376. The failure is occurring because Dependabot PRs use a separate secret source.
To resolve this, I've added `if: github.secret_source == 'Actions'` so that DockerHub and GHCR login steps are skipped for Dependabot PRs. Additionally, I've set `push: ${{ github.secret_source == 'Actions' }}` to build Docker images, but skip the push stage.
Although GHCR login would still pass for Dependabot PRs, I added the if statement to both DockerHub and GHCR login steps for consistency.
=> Skip Docker push for Dependabot PRs

.env.template, recipes/settings.py
I like running on debug mode all of the time, but the toolbar adds a very noticeable drag on performance (plus my other users don't need to see it)
This lets you turn on debug and the toolbar seperately.
=> enable toolbar seperate from debug logging

.env.template, docs/features/authentication.md, recipes/settings.py
Currently connctions to LDAP servers which require secure connections initiated via StartTLS are not possible. This change adds the environment option `AUTH_LDAP_START_TLS` and forwards it to the ldap provider (https://django-auth-ldap.readthedocs.io/en/latest/reference.html#auth-ldap-start-tls), so one can optionally enable StartTLS.
=> ldap auth: allow connecting using StartTLS

.github/workflows/build-docker.yml
This PR fixes #2436 by using `GITHUB_REF` instead of relying on a release event payload.
This is untested since I don't have a Discord bot set up, but I'll attempt a release in my fork and ensure the env gets set correctly. The docs for [Ilshidur/action-discord](https://github.com/Ilshidur/action-discord#arguments) say that `{{ ... }}` can be used for environment variables, so this _should_ work just fine.
=> Fix stable release Discord notification

cookbook/forms.py
Due to [1], the previous solution does not work on recent Django releases.
See [2] for the documented work-around, as applied in this commit.
Closes #2457.
[1]: https://docs.djangoproject.com/en/4.2/releases/4.2.1/
[2]: https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/#uploading-multiple-files
=> Fix multiple file field

.env.template, boot.sh
While helping to debug some gunicorn startup issues I realized that the gunicorn log level was not yet configurable. So I modified the .env file and boot.sh script to make the gunicorn loglevel configurable by setting the `GUNICORN_LOG_LEVEL` variable. 
We could maybe also use the DEBUG variable to modify the gunicorn log level as well I'm open to both possibilities.
=> Enable gunicorn debug log

cookbook/admin.py
creates two admin actions:
- delete all Ingredients not part of a recipe
- delete all Steps not part of a recipe
=> add admin command to delete unattached ingredients and steps

vue/src/components/BottomNavigationBar.vue
Currently, the mobile navigation bar shows up at the bottom of each page when printing, as shown below:
=> Fix bottom navigation not hiding in print mode

docs/install/docker/ipv6_plain/docker-compose.yml, docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/plain/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml, docs/install/swag.md, docs/install/truenas_portainer.md
These are some small Improvements to the docker-compose files in the docs:
1. Postgres version 11 is the default in the docker-compose files and its support will end in [November](https://www.postgresql.org/support/versioning/). Is there any reason against updating it to the most recent version?
2. Since many support requests in the discord boil down to the fact that the nginx config volume was changed to a bind mount and nginx can't find its config anymore, I added a small disclaimer which should make it clear that it shouldn't be changed without consideration.
=> add note to docker-compose files and update postgres tag

cookbook/serializer.py
This adds the `source_url` field to the recipe export. It's present in other export types (e.g. Paprika) but missing from the default export.
=> Add source URL to recipe export

.env.template, recipes/settings.py
I've been fighting with CORS and CSRF (amongst other things) while trying to get an API call with ajax to work. As such, I found that `CORS_ORIGIN_ALLOW_ALL` was fixed as `True`. I feel that it should be configurable by the user, so I added an `os.getenv` call for it with a default to `True` for no breaking changes. I also updated it per https://github.com/adamchainz/django-cors-headers to `CORS_ALLOW_ALL_ORIGINS`.
I added that and `CSRF_TRUSTED_ORIGINS` to the template .env file for better discoverability, though they're both commented out.
I didn't do a discussion on this first, but I can start one if that would be preferred.
=> Update and add settings

.env.template, cookbook/helper/AllAuthCustomAdapter.py, docs/features/authentication.md
When a social provider is set up, the social account signup view is enabled. This seems to cover issue #2261, but it needs further testing.
=> allow signup for social accounts when the provider is set up

cookbook/serializer.py, cookbook/views/api.py
=> fix recipe counting issue on extended mixin

.env.template, boot.sh
This commit adds two optional environment variables:
- SECRET_KEY_FILE
- POSTGRES_PASSWORD_FILE
This change allows mounting secret data when running this in Docker Swarm, instead of having to hard-code it in our docker-compose file or provide it alongside all other environment variables.
=> Added support for keeping SECRET_KEY and POSTGRES_PASSWORD in a file

vue/src/apps/ImportView/ImportView.vue
The page showing the list of apps you can import recipes from could work better on small screens. Here's a gif of the current behaviour:
I have added some breakpoints to the grid of apps so that they are easier to read on smaller screens.
Now the names of the apps can be easily read on small screens. However when all the apps are in such a long list it might be confusing for the user to have to scroll down all the way to the bottom to import the file. I think also that maybe when pressing an app the file chooser should open immediately and the bottom section of the page should be removed? Or maybe the bottom part opens as a modal? Despite this potential confusion I think the layout change is still preferable to the current behaviour as right now this page is almost unusable on a phone.
=> Make import list layout responsive

vue/src/apps/RecipeEditView/RecipeEditView.vue
When deleting steps and ingredients I was sometimes unsure which delete button I'd actually pressed. I've tweaked the strings to now tell the user what they're about to delete.
e.g. 
- Steps
- without a name
`Are you sure you want to delete this Step?` |-> `Are you sure that you want to delete Step "2"`
- with a name
`Are you sure you want to delete this Step?` |-> `Are you sure that you want to delete Step "Prepare vegetables"`
- Ingredients
- without a name
`Are you sure you want to delete this Ingredient?` (unchanged)
- with a name
`Are you sure you want to delete this Ingredient?` |-> `Are you sure that you want to delete "cloves"`
=> Increase specificity of the delete confirmation dialog

cookbook/helper/open_data_importer.py
**Related to**
#2514
#2595 
#2676 
https://github.com/TandoorRecipes/open-tandoor-data/pull/11
The Problems Source is, the same as in #2595. The German translation of the Import File has duplicate entries for the different Foods.
The Fix i added in #2595 works and is still required for updating already imported lists. But i overlooked, that if the list was never previously imported the import would also fail trying to insert the duplicates.
This aims to fix that by introducing another check "if the food with name is already in the insert_list"
=> open-data-import further duplicate handling

.dockerignore, cookbook/views/api.py, vue/src/apps/ImportView/ImportView.vue, vue/src/locales/en.json, vue/src/utils/utils.js
This improves the error reporting when importing recipes via a URL. Currently, it will just throw an error without any further information. To fix this, I decided to just propagate the error returned by the backend via the standard toast. The limitation of this is, that there is no localization for the error message from the backend. If you see the need for this and an easy way to add it, please let me know!
Fixes #2596
=> Improve import error messages

recipes/settings.py
A recent change in the DATABASE_URL regex ignores the PORT and DB part when a port number is provided:
With this change it parses properly again:
=> Fix parsing DATABASE_URL with port number

vue/src/components/IngredientComponent.vue
Increases the touch/hover target size for the ingredients comments button. (I think there was already a mitigation for this but it didn't quite work)
The new target is about the width of the comment icon either side, before it was just the comment icon itself that was the touch/hover target
Also tweaks the vertical alignment of the icons in the row.
Before:
After:
=> Touchable fix

docs/faq.md
Hello,
I saw that instructions to install the PWA on Firefox for Android were missing, so I added them to the doc. I also fixed Chrome's heading level  (it was `h3` instead of `h4` like Safari)
=> Add instructions to add the PWA on Firefox for Android

boot.sh, nginx/conf.d/Recipes.conf
I'm using tandoor in a docker compose setup. I noticed that nginx sometimes returns a "Bad Gateway" error and logs something like `upstream server temporarily disabled while connecting to upstream`.
Although I'm not entirely sure, I think this might be caused by my IPv4/IPv6 dual stack setup (I've enabled ipv6 on the network created by docker compose). I assume the DNS request from the nginx container sometimes resolves to the IPv6 address of the gunicorn container. The gunicorn container does not listen to IPv6 connections. Therefore, the connection is refused and nginx returns a gateway error.
This PR binds gunicorn to `[::]:8080` instead of `:8080`. This should listen on [both IPv4 and IPv6](https://github.com/benoitc/gunicorn/issues/1138#issuecomment-158358666) addresses (as long as …
=> Make gunicorn and nginx listen to IPv6

vue/src/components/Buttons/RecipeSwitcher.vue, vue/src/components/RecipeCard.vue
Partially solves #2520 by adding scroll to long descriptions:
Bonus: match the border color of the quick action button aka recipe switcher on mobile with the hamburger menu button's border.
=> Fix description overflow

README.md
I noticed a very minor typo ("then" instead of "than") in the README, so I fixed it.
=> fix tiny typo in README

docs/system/updating.md
During the steps to re-import a PostgreSQL dump, the tool `psql` is used twice.
On first usage, the database and user role are specified: https://github.com/TandoorRecipes/recipes/blob/5129ef77c96fb27e08067f72600f3f4a0a76c6c5/docs/system/updating.md?plain=1#L80
At the second time, `psql` is run without any arguments: https://github.com/TandoorRecipes/recipes/blob/5129ef77c96fb27e08067f72600f3f4a0a76c6c5/docs/system/updating.md?plain=1#L84
This gave me the following error:
```console
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
```
If I am not wrong, we should specify the database and user role here, as well. This is fixed by this merge request:
```shell
docker exec -it {{database_container}} psql postgres -U …
```
=> docs: specify database and user role when running psql

docs/install/docker.md
This PR provides additional information to serve tandoor images from an nginx reverse proxy by bind-mounting the `mediafiles` directory and then serving the images directly from the server, and resolves #2796 
Please feel free to make modifications to the documentation as needed to fit the style of the existing style.
Code/configuration released under AGPL.  I'm not sure how you all are releasing your documentation.  Let me know what license you need and happy to release it under those terms.
=> Updated nginx documentation to include image server instructions

docs/features/authentication.md
Keycloak was deprecated and removed in recent allauth version. This pr fixes the now outdated docs.
=> Fixed wrong keycloak docs

docs/features/authentication.md
- Allauth has changed the OIDC provider to use the APPS syntax instead of SERVERS
- The link to all providers was dead.
- Allauth recommends that a provider should be configured through only one method, and weird issues can arise when there's a conflicting provider_id via ENV and Django Admin.
- PKCE is starting to be very common and required, added that to the example. (Separate PR to improve openid_connect docs in django-allauth for that.)
=> docs(authentication): Improve auth docs to match current allauth best practices and syntax

docs/install/archlinux.md, mkdocs.yml
Hi,
For my own needs, I created a PKGBUILD to install TandoorRecipes on my ArchLinux based server. I've been using the package for several months by now, and at least one other user tested it: https://aur.archlinux.org/packages/tandoor-recipes-git#comment-924573
On ArchLinux, this package results in something similar to the [manual instructions](https://docs.tandoor.dev/install/manual/), but is easier to use, and should be more robust, since pacman can track installed files.
Are you interested in linking to this PKGBUILD, or to have it fully merged to this repository? For now, I'm proposing a new documentation page, but the package's sources are still hosted both on the AUR, and on my GitHub.
Let me know what you think of this. I can update the doc, or the package, to your requirements.
=> doc: Add installation instructions for ArchLinux

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/dependabot.yml, .gitignore, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, CONTRIBUTERS.md, docs/contribute.md
So I started down the path of wanting to write test for #2978, but didn't want to deal with venvs and messing around with installing random dependencies on my machine.  I've used devcontainers in the past to simplify creation of a development environment, and figured this would be great to simplify the development environment for tandoor.
=> Add devcontainer support

cookbook/views/views.py
In https://github.com/TandoorRecipes/recipes/pull/2730 the /system page was improved to warn the user if the version of Postgres they are using is out of date and should be updated. The current code attempts to determine the major versions by replacing `00` with `.` and then converting to a `Decimal`. Unfortunately, it appears the only value this method _does not_ work for are initial releases of major versions, like `16.0.0`.
For reference, either Postgres or the PsyCog driver represents the semver values but without the dots, so `16.0.0` becomes `1600000`.
This change removes the string replace and Decimal conversion in favor of using the [`divmod()` function](https://docs.python.org/3/library/functions.html#divmod). In this application it will return a tuple with the first element …
=> bug: Fix decimal.InvalidOperation on /system for some PG versions

cookbook/views/api.py, vue/src/apps/ShoppingListView/ShoppingListView.vue, vue/src/stores/ShoppingListStore.js
=> Shoppinglist fix

cookbook/views/views.py
In https://github.com/TandoorRecipes/recipes/pull/3027 I mistakenly forgot a `[0]` to index into the resulting tuple from a `divmod` call. 🤦
Added the index and then also wrapped everything in a try/catch to prevent future issues.
* Introduced in https://github.com/TandoorRecipes/recipes/pull/3027
* Closes #3053
=> bug: Fix TypeError at /system due to invalid PostgreSQL values [Closes #3053]

vue/src/components/PropertyViewComponent.vue
fix for issue #3091 
Function roundDecimals was not being called in PropertyViewComponent b-modal element so food properties were not being rounded to the specified number of decimals. 
Here is a side by side comparison of the bug before and after the fix, using the same numbers.
=> fix: rounding units

cookbook/integration/nextcloud_cookbook.py
=> Fix #3060 Next Cloud handle special ingredients ## 

Dockerfile, boot.sh
`collectstatic` and `collectstatic_js_reverse` both have dependencies on `.env` variables.  They can't be built independent of the environment they are going to run in.
=> removing pre-cached staticfiles from Docker & boot.sh

docs/install/docker/ipv6_plain/docker-compose.yml
Per my other PR, "version" is obsolete and throws a warning.
*NOTE:* This PR shows two changes, one to the `config: subnet` entry. I have **no idea** why a change is showing to that entry. I did _not_ make any change, and I also can't see what the change is supposed to be. Maybe it has something to do with line endings? I have created this PR twice, hoping the second time to avoid the second change that is not a change. I couldn't do it.
=> Remove obsolete "version:" entry

docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml
Per my other PR, the "version" entry in `compose.yml` is obsolete. This PR completes the updating of the remaining two of those files.
NOTE: Ignore the first commit, for "Merge pull request #1 from TandoorRecipes/develop." That was me bringing my fork up-to-date. I'm still learning Git, so I'm afraid my commits are a little sloppy. But you can see that the only real changes are to the `compose.yml` files.
=> Delete obsolete "version" entry from last two compose.yml files

docs/install/docker/plain/docker-compose.yml
The "version: 3" entry is obsolete and throws a warning: 'version' is obsolete. AFAIK, there's no reason to keep it. There's a lengthy discussion of this issue in a different repo: https://github.com/jasonacox/Powerwall-Dashboard/issues/453
They got rid of "version" in that project. It seems like it should be removed here too.
=> Remove obsolete "version: 3" to eliminate warning message

cookbook/connectors/connector_manager.py, cookbook/connectors/homeassistant.py, docs/system/configuration.md, recipes/settings.py
required for #3213
Adds logging in the following format:
```log
Thread-1 (worker) DEBUG 2024-07-10 11:15:22,820 recipes.connector.worker received item.instance=<ShoppingListEntry: Shopping list entry 77> with item.actionType=<ActionType.CREATED: 1>
Thread-1 (worker) DEBUG 2024-07-10 11:15:22,826 recipes.connector.worker running 1 connectors for item.instance=<ShoppingListEntry: Shopping list entry 77> with item.actionType=<ActionType.CREATED: 1>
Thread-1 (worker) DEBUG 2024-07-10 11:15:22,826 recipes.connector.homeassistant.test adding item='4'
```
=> enable logging for whole project and add more logging to connectors

docs/install/manual.md
The code written in https://github.com/TandoorRecipes/recipes/blob/develop/cookbook/connectors/connector_manager.py makes use of features introduced in Python 3.10, such as the structural pattern matching (match and case) and the union types with the pipe operator ( | ) which are not compatible with Python 3.9. That's why the minimum required python version for the manual installation should be python version 3.10.
=> Update manual.md with required python version

cookbook/integration/paprika.py
Previously, the code only tried to use the cropped image from paprika when downloading was attempted and **actively** failed. But if a user takes an image himself, the url field will be empty, thus downloading won't be attempted and won't fail. 
This resulted in no image being imported at all.
This change makes it so that the download is tried first, but the `photo_data` is always tried if no image exists after, for whatever reason.
=> Fix Paprika Import Images when not downloading from URL.

cookbook/integration/mealie.py
Fix following error during mealie  import:
```
ERROR 
null value in column "servings" of relation "cookbook_recipe" violates not-null constraint
DETAIL:  Failing row contains (304, Bechamel-Sauce, , , null, 0, t, 2024-10-12 13:47:31.576329+00, 2024-10-12 13:47:31.599914+00, 1, null, , 0, null, null, null, für 0,5 Liter Soße, None, 1, '0':2C '5':3C 'fur':1C 'liter':4C 'soss':5C, 'bechamel':2A 'bechamel-sauc':1A 'sauc':3A, null, t, f).
```
The error is caused by `"recipe_yield": null` in the exported recipes.
=> Fix null-constrait errors in mealie import

docs/install/manual.md
3.12 is necessary for image upload, according to the conversation in #3313 .
=> Add note about Python 3.12 dependency to manual.md

cookbook/templates/system.html
I guess this got left out when you renamed the project :)
=> Update system.html: Django Recipes > Tandoor

recipes/settings.py
The [documentation](https://docs.tandoor.dev/system/configuration/#debug) states that the Django DEBUG mode is disabled by default, and rightly points out that it should not be left enabled in production. 
This change aligns the code with the documentation, ensuring that people who run the app with default .env file don't end up with an unsecure configuration.
=> Disable DEBUG and DEBUG_TOOLBAR by default

cookbook/helper/image_processing.py
Fix #3573 
WebP is fully supported by Tandoor but the recent change that added restriction to file type removed the ability to upload webp files.
=> Add webp file as allowed file type

docs/install/synology.md
- Rewrote/revised most of the guide to bring it to current
- Previous guide was last updated several years ago and was largely depreciated. I moved the prior guide references to the end for historical purposes
- Added a depreciated warning under the Firewall section. I have been using the project for a week so far without a firewall rule set-up and have not had any issues.
=> Revise Synology Guide

docs/system/configuration.md, recipes/settings.py
You like the already existing `MEDIA_ROOT`
My usecase is to have both the media and staticfiles root outside of the `/opt/recipes/` directory to avoid `subPath` mounting on Kubernetes.
It felt missing since `MEDIA_URL` and `MEDIA_ROOT` exist but only `STATIC_URL`.
=> feat: introduce STATIC_ROOT env var

docs/system/updating.md
Fixed the documentation regarding updating postgres. Following changes were made:
- removed `sudo` to be more uniform in this documentation. The user should know in which right environment they had installed tandoor
- updated the `docker-compose` executable to `docker compose`
- added to step 6 the very neccessary information, that only `db_recipes` should be started in this point
=> Fix doc updating postgress

vue3/src/apps/tandoor/main.ts, vue3/vite.config.ts
Fixes #3903 
In `vue3/vite.config.ts`, as recommended in the docs: https://vite.dev/guide/build.html#relative-base we use a relative path. I was able to confirm it was not introducing issues when building the app and serving it from the dev server.
Then for SPA navigation, we need to init the router with the base URL. This is done when instantiating the router, so we retrieve the base URL injected by the backend and extract the path if there's one, or defaulting to `undefined`, which is the default behaviour if there is none: https://router.vuejs.org/api/functions/createWebHistory.html#Function-createWebHistory-
=> fix(vite): Configure Vite to use subfolder

cookbook/helper/image_processing.py
In the previous version of Tandoor I could upload some videos in the steps to document some specific process. Now this seems impossible.
Although I can still download the videos that were uploaded in the latest version.
This pull request adds two "file" types in the allowed list, .mp4 and .mov.
=> Allow video file types to be uploaded

docs/install/manual.md
Since v2 tandoor added user session tracking which requires the reverse proxy to add an extra header.
This change adds the `X-Forwarded-For` header to the example nginx configuration. This header fixes the issue described in #3943.
=> Update nginx configuration for manual setup

docs/install/synology.md
Hi,
i just recently upgraded Tandoor to 2.2.3 and noticed the information box in the docs.
Therefore i wanted to update the documentation:
- firewall is still necessary for the containers to talk to each other
- reverse proxy is also necessary if a user doesn't want to add the port to the firewall (in the SSL section there is some information how to allow the reverse proxy port in the firewall, i added this to the firewall information as well)
=> Synology documentation update Tandoor 2
