TandoorRecipes/recipes

cookbook/provider/nextcloud.py
otherwise I get an error (webdav3.exceptions.RemoteResourceNotFound: Remote resource: </path> not found)
=> added 'webdav_root' option

README.md, docs/k8s/10-configmap.yaml, docs/k8s/30-pv.yaml, docs/k8s/30-pvc.yaml, docs/k8s/50-deployment.yaml, docs/k8s/60-service.yaml, docs/k8s/README.md
Hey, I got it done faster than I expected :smile: 
Please take a look if you like it like this!
Closes #50
=> Kubernetes manifests

cookbook/templates/recipe_view.html
=> Show amounts even when unit is empty

recipes/settings.py
Addresses some of the issues brought up in #143.
=> Permit MEDIA_URL and STATIC_URL to be set from environment variables

cookbook/models.py, cookbook/templates/meal_plan.html, cookbook/views/api.py, requirements.txt
Hi again!
Since nobody implemented random recipes (#5) yet, I've put together my own. It doesn't do any fancy tag filtering yet, but shows 5 random recipes on loading the meal plan and adds a button to load another 5.
Feel free to reject this if you don't like the way it's done, I just wanted to share what I'm running on my fork.
Cheers!
=> Show random recipes in meal planner

cookbook/views/api.py
=> Include random in filtermixin

docs/docker/synology/README.md
Fixed env folder to .env folder and added instruction to set postgres password
Added information how to setup ssl and a task to update ssl certificate when needed
=> Update Synology Setup Readme

cookbook/serializer.py
Fixes https://github.com/vabene1111/recipes/issues/296
=> Assign authenticated user to created_by

README.md, docs/install/docker.md
This mostly fixes documentation formatting, but there are a few minor changes to the new Docker commands and templates.
=> Improve documentation formatting

cookbook/templates/base.html
=> Solving Apple web app issue

docs/install/other.md, recipes/settings.py
=> Add environment variable to include Sub-Path in resolve.js.

vue/src/apps/RecipeView/RecipeView.vue
=> Fix height issues in Safari by removing height rules

cookbook/locale/it/LC_MESSAGES/django.po
Italian translation updates.
Manual PR since Transifex doesn't do it.
=> Update Italian Translation

cookbook/helper/recipe_url_import.py, cookbook/views/api.py
also added description import when using direct json import
=> fix json direct import when wrapped in @graph

cookbook/filters.py
RecipeFilter was only checking for postgresql_psycopg2 - added postgresql
=> fix backend detection

cookbook/tests/api/test_api_ingredient.py, cookbook/tests/api/test_api_recipe.py, cookbook/tests/api/test_api_recipe_book.py, cookbook/tests/api/test_api_step.py, cookbook/tests/api/test_api_unit.py
updated tests so that they all pass when running in batch mode.
=> fixed tests to work in batch mode

cookbook/templates/base.html
Edited some strings in nb_NO, seems to work.
Plenty of errors in the source strings.
=> Spelling: Log out

cookbook/helper/recipe_url_import.py, cookbook/helper/scrapers/scrapers.py, cookbook/templates/url_import.html, cookbook/tests/other/_recipes.py, cookbook/views/api.py, cookbook/views/data.py
They changed a lot on how the scraper works, so I had to rework some of the logic.  it is really repetitive now, but it works and all the tests pass now.
=> updated to handle new behavior of recipe_scrapers

docs/install/docker/nginx-proxy/docker-compose.yml
=> Fix nginx_proxy docker-compose example

cookbook/helper/permission_helper.py, cookbook/views/views.py
addresses feature request #564
=> login redirect to intended page

cookbook/tests/other/_recipes.py, cookbook/tests/other/test_url_import.py, requirements.txt
url imports all pass now.
doublecheck the file path change you made - i had to fix it to work on linux  are paths different between linux/windows?
=> bumped recipe_scrapers and updated expected results

cookbook/helper/recipe_url_import.py, cookbook/tests/other/_recipes.py, cookbook/tests/other/test_data/chefkoch2.html, cookbook/tests/other/test_url_import.py
removed if statement checking if ingredient name exists from ingredient_from_text parser
added test to check for condition using recipe reported in #666
=> fix url import

cookbook/models.py, cookbook/tests/api/test_api_cook_log.py, cookbook/tests/api/test_api_import_log.py, cookbook/tests/api/test_api_sync_log.py, cookbook/tests/api/test_api_view_log.py, cookbook/views/api.py, vue/src/utils/openapi/api.ts
fixes #484 
made some guesses on expected behavior, added comments as to choices.  Validate before merging
=> implemented pagination on Log apis

cookbook/views/data.py
switched automation in URL import to IngredientParser class
=> fix automation in url_import

cookbook/helper/recipe_search.py
=> fix for #942

cookbook/helper/recipe_search.py
related to #943 
simplified the annotation for sorting recently viewed recipes, should be slightly faster
=> minor change on recent recipe search

docs/features/authentication.md
Added a basic how-to description of the LDAP usage in the authentication page of the documentation.
=> Added LDAP usage in documentation

docs/features/templating.md
Fix bad variable naming in docs
=> Fix Templating documentation

docs/install/kubesail.md, mkdocs.yml
Thanks for inviting me to add the KubeSail install to the docs!
Also, with PiBox our goal is to support open source devs, so after the Kickstarter is over and we're selling them on our website, we plan on donating a healthy portion of the sale if the traffic originates from the Tandoor docs or site (similar to how the amazon affiliate program works). We're still working out details, but if you have a Stripe account I think this should be pretty straightforward if you're interested. Will let you know once we get our shop set up!
I commented out the `A portion of every...` sentence until we actually get this in place :)
=> Add KubeSail install method

.github/workflows/docs.yml, docs/contribute.md, docs/install/docker.md, mkdocs.yml
This change includes docker-compose.yml files inline in the documentation built by `mkdocs`.
It ensures the documentation is always on-par with the files commited.
=> Docs: Inline docker-compose.yaml files in the documentation

.github/workflows/docs.yml, docs/contribute.md, docs/install/docker.md, mkdocs.yml
Reverts TandoorRecipes/recipes#1058
=> Revert "Docs: Inline docker-compose.yaml files in the documentation"

vue/src/apps/RecipeView/RecipeView.vue
closes #1067
Renders ingredients for each step in its own flex row with an optional title **before** the table.
Disclaimer: I never woked with vue before, so this might contain some glaring beginner mistakes 😉
=> Render separate ingredients flex row for each step 

docs/install/docker.md
=> Add documentation about swag by linuxserver

vue/src/apps/ModelListView/ModelListView.vue, vue/src/apps/RecipeSearchView/RecipeSearchView.vue
=> Search pagination

docs/install/docker.md
First commit was done in rush. Fixed a couple of punctuations.
=> punctuation fixes

cookbook/helper/recipe_html_import.py
=> fixes 1129

cookbook/templates/base.html
=> fixes 1123

recipes/settings.py
=> fix logout redirect

cookbook/helper/scope_middleware.py
fixes #1158 and might fix #1135
=> added prefix to request.path.startswith() conditionals

cookbook/views/api.py
=> ConnectError fail gracefully during URL import

cookbook/templates/manifest.json
=> change manifest paths to be relative

docs/install/docker.md
Since there have been quite some people with basic docker setup issues when using a reverse proxy and very basic reverse proxies like a nginx running locally as a proxy or Caddy, I figured these added sentences might clear things up for some people.
Feel free to suggest additional topics which should be added or refined.
=> Some additional info for reverse proxy setups.

.github/ISSUE_TEMPLATE/bug_report.yml
Added Apache2 as selectable option in the bug report template
=> Added Apache2 in the bug report template

docs/install/docker.md, docs/install/swag.md
Basic step-by-step swag install and configuration as requested in #1313.
=> add swag config example

vue/src/apps/ModelListView/ModelListView.vue, vue/src/components/Modals/LookupInput.vue, vue/src/utils/utils.js
=> fix supermarket categories

vue/src/apps/RecipeSearchView/RecipeSearchView.vue
added handle to address using keywords/foods from both treeselect and multiselect
=> fix multiselect

.github/ISSUE_TEMPLATE/doc_issue.yml
Added GH template for documentation issues.
Feel free to adjust.
=> Added GH template for documentation issues

vue/src/apps/ShoppingListView/ShoppingListView.vue, vue/src/components/IngredientsCard.vue, vue/src/components/Modals/ShoppingModal.vue
Add recipe from shopping list
change servings from shopping modal
add new shopping list entries discovered during autosync
move Undefined to top of list when supermarket selected
=> Add recipe from shopping list

cookbook/helper/shopping_helper.py, cookbook/serializer.py, cookbook/signals.py, cookbook/templates/shopping_list.html, cookbook/views/api.py, vue/src/apps/ModelListView/ModelListView.vue, vue/src/apps/RecipeSearchView/RecipeSearchView.vue, vue/src/apps/ShoppingListView/ShoppingListView.vue, vue/src/components/Badges/Help.vue, vue/src/components/Badges/Shopping.vue, vue/src/components/ContextMenu/ModelMenu.vue, vue/src/components/IngredientComponent.vue, vue/src/components/Modals/CheckboxInput.vue, vue/src/components/Modals/GenericModalForm.vue, vue/src/components/Modals/LookupInput.vue, vue/src/components/Modals/TextInput.vue, vue/src/locales/en.json, vue/src/utils/models.js, vue/src/utils/openapi/api.ts, vue/src/utils/utils.js
fix #1419 
add ignore_shopping back to food
stop hiding 'inherit fields' when there is no parent 
hide 'inherit fields' when there are no children present in space
add help text to GenericModal
fix #1414
=> Minor fixes

vue/src/components/MealPlanEditModal.vue, vue/src/components/Modals/ShoppingModal.vue, vue/src/components/RecipeContextMenu.vue
=> fix servings reactivity

cookbook/helper/permission_helper.py, cookbook/helper/shopping_helper.py, cookbook/migrations/0168_add_unit_searchfields.py, cookbook/models.py, cookbook/serializer.py, cookbook/signals.py, cookbook/tests/api/test_api_shopping_list_entryv2.py, cookbook/tests/api/test_api_shopping_recipe.py, cookbook/views/api.py, vue/src/apps/MealPlanView/MealPlanView.vue, vue/src/apps/RecipeSearchView/RecipeSearchView.vue, vue/src/apps/RecipeView/RecipeView.vue, vue/src/apps/ShoppingListView/ShoppingListView.vue, vue/src/components/GenericMultiselect.vue, vue/src/components/IngredientComponent.vue, vue/src/components/IngredientsCard.vue, vue/src/components/MealPlanCard.vue, vue/src/components/MealPlanEditModal.vue, vue/src/components/Modals/ShoppingModal.vue, vue/src/components/RecipeContextMenu.vue, vue/src/components/ShoppingLineItem.vue, vue/src/locales/en.json
=> Mealplan shopping useability

docs/faq.md
=> add instructions for pwa for Android/Chrome browsers

cookbook/helper/recipe_search.py, cookbook/helper/shopping_helper.py, cookbook/serializer.py, cookbook/templates/base.html, cookbook/views/api.py, cookbook/views/views.py, vue/src/apps/RecipeEditView/RecipeEditView.vue, vue/src/apps/ShoppingListView/ShoppingListView.vue, vue/src/components/GenericMultiselect.vue
resolves #1509
resolves #1507
resolved #1494
=> various fixes

cookbook/views/views.py, vue/src/apps/RecipeEditView/RecipeEditView.vue, vue/src/locales/en.json
=> paste list of ingredients

cookbook/views/views.py, vue/src/components/MealPlanEditModal.vue
=> fix duplicate shopping recipes when auto-add enabled

vue/src/components/RecipeContextMenu.vue, vue/src/locales/en.json
=> copy to new recipe

vue/src/components/StepComponent.vue
Fix for https://github.com/TandoorRecipes/recipes/issues/1545 by changing `recipe.file_path` to `step.file.file`.
=> fix file path checks

cookbook/forms.py, cookbook/helper/recipe_search.py, cookbook/serializer.py, cookbook/views/import_export.py, vue/src/apps/ExportResponseView/ExportResponseView.vue, vue/src/apps/ExportView/ExportView.vue, vue/src/apps/RecipeSearchView/RecipeSearchView.vue
=> Export from filter

cookbook/helper/shopping_helper.py
=> return distinct shopping entries

cookbook/helper/recipe_url_import.py, cookbook/integration/copymethat.py, cookbook/integration/recettetek.py, cookbook/integration/recipekeeper.py, cookbook/templates/url_import.html, vue/src/locales/de.json, vue/src/locales/en.json
=> Added a few more strings to be localized and fixed one ui alignment

cookbook/helper/template_helper.py
Allow using img tag in markdown and additionally allowing to specify
width and height attribute for elements.
=> Allow img tag (including width/height attribute)

docs/install/docker.md
Adds warning that the jwilder nginx-proxy reduces file size upload to 1 MB.
=> Updates Docker installation docs

docs/install/docker.md
I added too many ! and it did not format properly.
=> Fixes the formatting

cookbook/serializer.py
Fixes https://github.com/TandoorRecipes/recipes/issues/1689
=> Get image from S3-storage if configured

CONTRIBUTERS.md, cookbook/managers.py, recipes/settings.py
- Added Swedish in frontend
- Added Swedish in search
- Updated CONTRIBUTERS.md with my username
- Fixed CONTRIBUTERS.md after recommendation from markdown linter
=> Add swedish language support

vue/src/components/RecipeCard.vue
This is a quick change to the Recipe Card styling to resolve [#1287](https://github.com/TandoorRecipes/recipes/issues/1287). This is my first open source pull request ever so forgive me for my lack of knowledge hahaha.
=> Add clickable keywords to recipe card

docs/index.md
Added capitalization to line 52 and proposed some bold-face changes in lines 42, 44. 52. and 54.
=> Update index.md for capitalization and bold-face issues

cookbook/management/commands/export.py, cookbook/management/commands/import.py
=> Add django-scopes compatible django-admin dumpdata/loaddata commands

docs/contribute.md
Spotted several errors in sentence structure, punctuation, capitalization and other grammatical issues. Most changes are minor and any sentences that have been restructured have been re-written with great contemplation to keep the original meaning intact. This is my first open source contribution attempt so please let me know if this is appropriate. I am willing to help improve other pages of the docs as well if this work is considered helpful!
=> Grammatical errors

docs/install/manual.md
Updated the manual installation file to get everybody up and running.
There were missing requirements like the nginx installation and so on.
Now a first time linux user should be able to get this up and running.
=> Updates with more packages

cookbook/models.py, cookbook/tests/api/test_api_food.py
Through is populated on the class, so a food instance isn't needed.
=> Fixes #1857

docs/system/backup.md
Added manual backup method first draft
=> Update backup.md with manual process 

cookbook/integration/cookbookapp.py
=> updated cookbookapp importer to handle multi-step recipes

docs/system/migration_sqlite-postgres.md
As promised in issue #79. I successfully performed my migration and documented all steps I took for future use.
=> Add documentation for migrating from sqlite3 database to postgresql (Unraid)

cookbook/integration/copymethat.py
improve handling of empty fields and fields that exceed character limits
=> fix minor issues in CopyMeThat importer

vue/src/apps/ShoppingListView/ShoppingListView.vue
Added number of items in each tabs array to the tabs title.
=> Fixes  #1234

cookbook/locale/tr/id/LC_MESSAGES/django.po
will update regularly until finish
=> add indonesian language

docs/install/docker/plain/docker-compose.yml
Reverts TandoorRecipes/recipes#2128
=> Revert "Fixed: ports are on the wrong service"

docs/faq.md
Hi, I added a number of correction and punctuation fixes.
=> added a couple of typo corrections

cookbook/integration/openeats.py, docs/features/import_export.md
Updated the code to be able to parse tags, cuisine and course out of OpenEats. Also parses comments and ratings and allows for transfer of images from OpenEats.
Documentation updated to include process of how to import the extra data
=> Improve parsing of OpenEats imports

cookbook/locale/de/LC_MESSAGES/django.po
Very cool project! 
As a native German speaker this instantly stood out to me, so here is a quick fix
=> Small fix for german language

cookbook/helper/recipe_url_import.py
=> added keyword automation to url import

cookbook/helper/recipe_search.py, cookbook/tests/api/test_api_food.py, cookbook/tests/api/test_api_shopping_recipe.py, cookbook/tests/conftest.py, cookbook/tests/factories/__init__.py, cookbook/tests/other/test_makenow_filter.py, cookbook/tests/other/test_recipe_full_text_search.py, recipes/settings.py, requirements.txt, vue/src/components/IngredientComponent.vue
=> Pytest fixes

cookbook/templates/base.html
Search engines should not index personal `recipes` pages.
=> Prevent indexing content by search engines

vue/src/apps/RecipeSearchView/RecipeSearchView.vue
=> update Meal Plan grid to respect localization on date format

cookbook/helper/shopping_helper.py, cookbook/views/api.py, vue/src/components/Modals/ShoppingModal.vue
=> respect ignore_shopping flag

vue/src/components/GenericMultiselect.vue
=> clears search on food in shopping form

cookbook/integration/default.py, cookbook/integration/integration.py, cookbook/views/import_export.py, vue/src/apps/ExportView/ExportView.vue
fixes #2601 
and I think it also resolves #2158
=> fix custom_filter exports and errors on Download link

docs/install/manual.md
In this PR virtual environment activation step is added.
closes https://github.com/TandoorRecipes/recipes/issues/2479
=> add step on docs for manual installation

cookbook/forms.py, cookbook/templates/export.html, cookbook/templates/export_response.html, vue/src/apps/ExportResponseView/ExportResponseView.vue, vue/src/apps/ExportView/ExportView.vue
=> fixes recipe export

.gitignore, boot.sh, cookbook/admin.py, cookbook/helper/recipe_search.py, cookbook/management/commands/rebuildindex.py, cookbook/migrations/0143_build_full_text_index.py, cookbook/signals.py, cookbook/tests/api/test_api_shopping_recipe.py, cookbook/tests/other/test_recipe_full_text_search.py, cookbook/views/api.py, cookbook/views/views.py, docs/install/k8s/50-deployment.yaml, recipes/settings.py
changed DATABASE_URL regex to support sqlite syntax
create directory for sqlite if it doesn't exist
changed boot.sh to only require password if engine is postgres
remove references to deprecated postgresql_psycopg2
=> better support for sqlite

cookbook/helper/HelperFunctions.py, cookbook/helper/recipe_search.py, cookbook/templates/system.html, cookbook/version_info.py, cookbook/views/views.py, recipes/settings.py, version.py, vue/src/apps/RecipeSearchView/RecipeSearchView.vue
orphaned file view added to System page
=> view and delete orphaned files

cookbook/admin.py, cookbook/models.py
updates to various admin pages
=> Admin updates

docs/faq.md
I improved the understandability some parts in the psql examples for someone not familiar with the psql syntax.
=> Improved the understandability of the postgres upgrade steps

docs/system/backup.md
Fixed a small typo in the documentation.
=> docs: fix typo

cookbook/helper/template_helper.py
=> add: support to scale numbers/amounts in a recipe step

docs/install/docker/ipv6_plain/docker-compose.yml, docs/install/docker/nginx-proxy/docker-compose.yml, docs/install/docker/plain/docker-compose.yml, docs/install/docker/traefik-nginx/docker-compose.yml, docs/install/swag.md, docs/install/truenas_portainer.md
Update postgres version in documentation to meet the version set in code
see https://github.com/TandoorRecipes/recipes/blob/e5303967df46af602dd42c397bd3a32a1c6e3eef/cookbook/views/views.py#L335
=> Update postgres in documentation

cookbook/helper/automation_helper.py
=> regex replace not run on food if there are no food aliases

cookbook/connectors/homeassistant.py, requirements.txt
=> use normal async client for api calls

Dockerfile, boot.sh
This reapplies #3055 and fixes the problems caused by the PR (#3099).
=> improve docker run speed

README.md
Corrected link to the code contribution docs within the Contributing section of readme
=> Update link in Contributing section of readme

cookbook/helper/recipe_url_import.py, cookbook/views/api.py
recipe-scrapers always requires an URL, provide a fake one if none provided
fixes #3267
=> set URL when none provided

cookbook/templates/base.html
This PR fixes the typo of 'Tandoor' as per the issue #3271 .
=> Fixed the typo in the base.html file

docs/features/connectors.md
Reverts TandoorRecipes/recipes#3326
=> Revert "Update connectors.md"

cookbook/forms.py, cookbook/integration/gourmet.py, cookbook/integration/integration.py, cookbook/views/import_export.py, docs/features/import_export.md, vue/src/utils/integration.js
* in gourmet export as html and zip folder
* 'menus' are not imported
Note: it appears that the native format '.grmt' does not include the unit for ingredients
=> import of gourmet files

cookbook/views/api.py, vue/src/apps/ImportView/ImportView.vue
=> Display a warning message when duplicate recipe is imported

cookbook/integration/paprika.py
Addresses #3494 with proposed resolution.
=> Prevent paprika.py from importing empty image_url content

docs/contribute/related.md
The refered mobile app is discontinued and another one is suggested there.
=> docs: mobile apps updated

vue3/src/pages/RecipeImportPage.vue
This should fix #3667
I haven't tested this code in a dev environment, I only manually edited my bookmarklet and it works now.
=> fix bookmarklet

boot.sh, docs/system/configuration.md
(I can re-target this against `feature/vue3` if that would be better.)
Thank you for the excellent project! Looking forward to the Vue 3 UI.
=> Support reading S3_SECRET_ACCESS_KEY from file

README.md, docs/index.md
Added links to the community forum.
Took the liberty to remove Twitter links.
I'd suggest to also add a link to the community to the Contact footer on https://tandoor.dev
=> add community links

.devcontainer/Dockerfile, .vscode/tasks.json, docs/contribute/vscode.md
=> Update devcontainer to work with new vue3 UI.
